language: node_js
sudo: false
node_js:
    - "5.0"
    - "5.11"
    - "6"

cache:
  directories:
    - node_modules

notifications:
  email: false

branches:
  only:
    - develop
    - master

before_script:
    - npm install

# todo: configure coverage reports
script:
  - npm run test
  #- npm run test:coverage
  #- codecov
  #- npm run send-cover-report

after_success:
  - bash <(curl -s https://codecov.io/bash)