language: python

sudo: false

python:
  - "2.7"
  - "3.5"
  - "3.6"

install: pip install -r requirements.txt

script:
  - python manage.py test

allow_failures:
  python:
    - "3.6"

after_success:
  - bash <(curl -s https://codecov.io/bash)

