language: python

sudo: false

python:
  - "2.7"
  - "3.5"
  - "3.6"

install: pip install -r requirements.txt

script:
  - python manage.py init_async_values
  - python manage.py test
  - python-codacy-coverage -r coverage.xml
  - codecov

allow_failures:
  python:
    - "3.6"

after_success:
  - bash <(curl -s https://codecov.io/bash)

