version: "3.0"

services:
  client:
    restart: always
    build: ./client
    ports:
      - "3000:3000"
    expose:
      - "5000"
    networks:
      - frontend
    volumes:
      - /usr/src/app/
    command: npm run start
    links:
      - "server:picloud"
    depends_on:
      - server

  server:
    restart: always
    build: ./server
    ports:
      - "5000:5000"
    expose:
      - "8000"
    volumes:
     - /usr/src/app/app/static
     - /media/picloud/
    command: python manage.py runserver
    links:
    	- "db:database"
    depends_on:
     - postgres
    networks:
      - backend
      - frontend

  redis:
    restart: always
    build: ./redis
    depends_on:
      - server
    networks:
      - backend

  data:
    image: postgres:9.6
    volumes:
      - /var/lib/postgresql
    command: "true"
    networks:
      - backend

  db:
    restart: always
    build: ./postgresql
    ports:
      - "5432:5432"
    networks:
      - backend

# define networks in which services will be visible to each other      
networks:
	frontend:
	backend:      
